"""Build paper/refs.bib from primary arXiv metadata. Never hand-type a citation.

arXiv rate-limits aggressively, so requests are spaced and the fetched metadata is
cached in paper/refs_meta.json. Re-running only fetches what is still missing.

Usage:  python src/make_bib.py [--spacing 45]
"""
import os, sys, json, time, argparse, urllib.parse, urllib.request
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.join(os.path.dirname(HERE), "paper")
CACHE = os.path.join(PAPER, "refs_meta.json")
NS = {"a": "http://www.w3.org/2005/Atom"}

# Cited in PREREGISTRATION.md section 1. key -> arXiv id.
REFS = {
    "bertalanic2026conformity": "2605.00914",
    "wu2025conformity":         "2511.07784",
    "zhu2025conformity":        "2510.10185",
    "stance2026":               "2606.00820",
    "speaker2026":              "2607.05545",
    "choi2025debatevote":       "2508.17536",
    "minority2025":             "2504.05047",
    "imad2025":                 "2511.11306",
    "sentinel2026":             "2606.29270",
}


def fetch(aid, timeout=45):
    u = "http://export.arxiv.org/api/query?" + urllib.parse.urlencode(
        {"id_list": aid, "max_results": 1})
    e = ET.fromstring(urllib.request.urlopen(u, timeout=timeout).read()).find("a:entry", NS)
    if e is None:
        raise LookupError(f"no entry for {aid}")
    return {"title": " ".join(e.find("a:title", NS).text.split()),
            "authors": [a.find("a:name", NS).text for a in e.findall("a:author", NS)],
            "published": e.find("a:published", NS).text[:10],
            "arxiv": aid}


def bibtex(key, m):
    authors = " and ".join(m["authors"])
    return (f"@article{{{key},\n"
            f"  title  = {{{m['title']}}},\n"
            f"  author = {{{authors}}},\n"
            f"  year   = {{{m['published'][:4]}}},\n"
            f"  journal= {{arXiv preprint arXiv:{m['arxiv']}}},\n"
            f"  eprint = {{{m['arxiv']}}},\n"
            f"  archivePrefix = {{arXiv}}\n}}\n")


def main(spacing=45):
    os.makedirs(PAPER, exist_ok=True)
    cache = json.load(open(CACHE)) if os.path.exists(CACHE) else {}
    todo = [(k, a) for k, a in REFS.items() if a not in cache]
    print(f"{len(cache)} cached, {len(todo)} to fetch", flush=True)
    for k, aid in todo:
        for attempt in range(3):
            try:
                cache[aid] = fetch(aid)
                json.dump(cache, open(CACHE, "w"), indent=1)
                print(f"  ok   {aid}  {cache[aid]['authors'][0]}", flush=True)
                break
            except Exception as ex:
                print(f"  retry{attempt} {aid} {repr(ex)[:60]}", flush=True)
                time.sleep(spacing * (attempt + 2))
        time.sleep(spacing)

    have = {k: cache[a] for k, a in REFS.items() if a in cache}
    with open(os.path.join(PAPER, "refs.bib"), "w") as f:
        f.write("% AUTO-GENERATED by src/make_bib.py from arXiv metadata.\n")
        for k in sorted(have):
            f.write(bibtex(k, have[k]) + "\n")
    missing = [k for k in REFS if REFS[k] not in cache]
    print(f"wrote {len(have)}/{len(REFS)} entries -> paper/refs.bib")
    if missing:
        print("STILL MISSING (do not hand-type; re-run):", missing)
    return missing


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--spacing", type=int, default=45)
    sys.exit(1 if main(ap.parse_args().spacing) else 0)
